name: news-recsys
channels:
  - pytorch
  - nvidia
  - pyg
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - pyg
  - pytorch-scatter
  - pytorch-sparse
  - pytorch-cluster
  - pytorch-spline-conv
  - pandas
  - numpy
  - scikit-learn
  - scipy
  - transformers
  - sentence-transformers
  - fastapi
  - uvicorn
  - python-multipart
  - httpx
  - matplotlib
  - seaborn
  - tqdm
  - tabulate
  - pyyaml
  - plotly
  - wordcloud
  - jupyter
  - pip
  - pip:
    - underthesea
    - pyvi
    - rank-bm25
    - gensim
